style:
  MaxLineLength:
    maxLineLength: 180
  ForbiddenImport:
    forbiddenPatterns:
      - org.junit.*
      - io.github.lexadiky.pdx.library.uikit.R


complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    ignoreDefaultParameters: true
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 20

naming:
  FunctionNaming:
    functionPattern: ([a-z][a-zA-Z0-9]*)|([a-zA-Z][a-zA-Z0-9]*Module)
    ignoreAnnotated:
      - Composable

exceptions:
  TooGenericExceptionCaught:
    active: false
