[versions]

android-compose = "1.3.0"

[libraries]

android-core = "androidx.core:core-ktx:1.9.0"
android-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
android-activity-compose = "androidx.activity:activity-compose:1.6.1"

android-compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "android.compose" }
android-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "android.compose" }
android-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android.compose" }
android-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "android.compose" }
android-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android.compose" }
android-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "android.compose" }

android-compose-material3 = "androidx.compose.material3:material3:1.0.0"

android-test-junit4 = "androidx.test.ext:junit:1.1.3"
android-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
junit4-core = "junit:junit:4.13.2"

[plugins]
