[versions]

android-compose = "1.3.0"
ktor = "2.1.3"
accompanist = "0.28.0"
akore = "-SNAPSHOT"
coroutines = "1.6.4"

[libraries]

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-gmsIntegration = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
kotlin-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
kotlin-reflection = "org.jetbrains.kotlin:kotlin-reflect:1.8.0"

android-core = "androidx.core:core-ktx:1.9.0"
android-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
android-activity-compose = "androidx.activity:activity-compose:1.6.1"
android-material = "com.google.android.material:material:1.8.0-alpha02"

android-compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "android.compose" }
android-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "android.compose" }
android-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android.compose" }
android-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "android.compose" }
android-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android.compose" }
android-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "android.compose" }
android-compose-material3 = "androidx.compose.material3:material3:1.1.0-alpha05"
android-compose-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-compose:2.5.1"
android-compose-glance = "androidx.glance:glance-appwidget:1.0.0-alpha05"

android-navigation-compose = "androidx.navigation:navigation-compose:2.5.3"

android-test-junit4 = "androidx.test.ext:junit:1.1.3"
android-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"

junit4-core = "junit:junit:4.13.2"

coil-compose-base = "io.coil-kt:coil-compose-base:2.2.2"

arrow-core = "io.arrow-kt:arrow-core:1.1.5"

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

firebase-bom = "com.google.firebase:firebase-bom:31.1.0"
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-remoteConfig = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-performance = { module = "com.google.firebase:firebase-perf-ktx" }

accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }

akore-blogger-core = { module = "com.github.akore-org.blogger:core", version.ref = "akore" }
akore-blogger-logcat = { module = "com.github.akore-org.blogger:logcat", version.ref = "akore" }
akore-alice-core = { module = "com.github.akore-org.alice:core", version.ref = "akore" }
akore-alice-robo = { module = "com.github.akore-org.alice:robo", version.ref = "akore" }

pokeapi = "com.github.lexa-diky:pokeapi-kotlin:-SNAPSHOT"

[plugins]
