name: Detekt Scan

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6
        with:
          arguments: detektAll
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt
